//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MECProject_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int service_ID { get; set; }
        public string service_name { get; set; }
        public Nullable<int> service_rate { get; set; }
        public Nullable<int> category_ID { get; set; }
        public string service_field1 { get; set; }
    }
}
