//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MECProject_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopkeeper
    {
        public int shopkeeper_ID { get; set; }
        public string shopkeeper_name { get; set; }
        public string shopkeeper_fname { get; set; }
        public string shopkeeper_shopname { get; set; }
        public string shopkeeper_shopaddress { get; set; }
        public string shopkeeper_email { get; set; }
        public string shopkeeper_phoneno { get; set; }
        public string shopkeeper_bank_account { get; set; }
        public string shopkeeper_password { get; set; }
        public Nullable<int> shopkeeper_commission { get; set; }
        public string shopkeeper_field1 { get; set; }
        public string shopkeeper_field2 { get; set; }
    }
}
